"use client";
import { ChangeEvent, FormEvent, useEffect, useMemo, useState } from "react";
import { createClient } from "@/lib/supabase/client";
type Profile={id:string;username:string;display_name:string;bio:string;avatar_url:string|null};
type Post={id:string;author_id:string;caption:string;media_path:string|null;media_type:string|null;created_at:string;profile?:Profile;likeCount:number;liked:boolean;commentCount:number;comments:{id:string;body:string;profile?:Profile}[]};
type Chat={profile:Profile;last:string;updated:string};
const blankAvatar=(name:string)=>"https://api.dicebear.com/9.x/initials/svg?seed="+encodeURIComponent(name)+"&backgroundColor=b6e35f&fontFamily=Arial&fontWeight=700";
export default function HomeClient({profile:initialProfile}:{profile:Profile}){
 const supabase=useMemo(()=>createClient(),[]);
 const [profile,setProfile]=useState(initialProfile),[screen,setScreen]=useState("home"),[posts,setPosts]=useState<Post[]>([]),[people,setPeople]=useState<Profile[]>([]),[query,setQuery]=useState(""),[followed,setFollowed]=useState<string[]>([]),[saved,setSaved]=useState<string[]>([]),[showCreate,setShowCreate]=useState(false),[caption,setCaption]=useState(""),[file,setFile]=useState<File|null>(null),[preview,setPreview]=useState(""),[posting,setPosting]=useState(false),[notice,setNotice]=useState(""),[chats,setChats]=useState<Chat[]>([]),[selected,setSelected]=useState<Profile|null>(null),[messages,setMessages]=useState<any[]>([]),[message,setMessage]=useState(""),[loading,setLoading]=useState(true);
 const avatar=(p:Profile)=>p.avatar_url||blankAvatar(p.display_name);
 async function loadProfile(){const{data}=await supabase.from("profiles").select("*").eq("id",initialProfile.id).single();if(data)setProfile(data);}
 async function loadPeople(){const{data}=await supabase.from("profiles").select("id,username,display_name,bio,avatar_url").neq("id",initialProfile.id).order("created_at",{ascending:false}).limit(50);setPeople(data||[]);const{data:f}=await supabase.from("follows").select("following_id").eq("follower_id",initialProfile.id);setFollowed((f||[]).map((x:any)=>x.following_id));}
 async function loadPosts(){const{data}=await supabase.from("posts").select("*").order("created_at",{ascending:false}).limit(50);const rows=data||[];const ids=[...new Set(rows.map((p:any)=>p.author_id))];const{data:ps}=ids.length?await supabase.from("profiles").select("*").in("id",ids):{data:[] as any[]};const pmap=new Map((ps||[]).map((p:any)=>[p.id,p]));const pids=rows.map((p:any)=>p.id);const{data:likes}=pids.length?await supabase.from("likes").select("post_id,user_id").in("post_id",pids):{data:[] as any[]};const{data:comments}=pids.length?await supabase.from("comments").select("id,post_id,user_id,body,created_at").in("post_id",pids).order("created_at",{ascending:true}):{data:[] as any[]};const uids=[...new Set((comments||[]).map((c:any)=>c.user_id))];const{data:cus}=uids.length?await supabase.from("profiles").select("*").in("id",uids):{data:[] as any[]};const cmap=new Map((cus||[]).map((p:any)=>[p.id,p]));setPosts(rows.map((p:any)=>({...p,profile:pmap.get(p.author_id),likeCount:(likes||[]).filter((l:any)=>l.post_id===p.id).length,liked:(likes||[]).some((l:any)=>l.post_id===p.id&&l.user_id===initialProfile.id),commentCount:(comments||[]).filter((c:any)=>c.post_id===p.id).length,comments:(comments||[]).filter((c:any)=>c.post_id===p.id).map((c:any)=>({...c,profile:cmap.get(c.user_id)}))})));const{data:s}=await supabase.from("saved_posts").select("post_id").eq("user_id",initialProfile.id);setSaved((s||[]).map((x:any)=>x.post_id));}
 async function loadChats(){const filter="sender_id.eq."+initialProfile.id+",recipient_id.eq."+initialProfile.id;const{data}=await supabase.from("messages").select("*").or(filter).order("created_at",{ascending:false}).limit(300);const rows=data||[];const ids=[...new Set(rows.map((m:any)=>m.sender_id===initialProfile.id?m.recipient_id:m.sender_id))];const{data:ps}=ids.length?await supabase.from("profiles").select("*").in("id",ids):{data:[] as any[]};const pmap=new Map((ps||[]).map((p:any)=>[p.id,p]));const latest=new Map<string,any>();rows.forEach((m:any)=>{const other=m.sender_id===initialProfile.id?m.recipient_id:m.sender_id;if(!latest.has(other))latest.set(other,m)});setChats([...latest.entries()].map(([id,m])=>({profile:pmap.get(id),last:m.body,updated:m.created_at})).filter((x:any)=>x.profile));}
 async function openChat(other:Profile){setSelected(other);const a="sender_id.eq."+initialProfile.id+" and recipient_id.eq."+other.id;const b="sender_id.eq."+other.id+" and recipient_id.eq."+initialProfile.id;const{data}=await supabase.from("messages").select("*").or("and("+a+"),and("+b+")").order("created_at",{ascending:true});setMessages(data||[]);}
 useEffect(()=>{Promise.all([loadProfile(),loadPeople(),loadPosts(),loadChats()]).finally(()=>setLoading(false));},[]);
 useEffect(()=>{const channel=supabase.channel("avenzo-chat-"+initialProfile.id).on("postgres_changes",{event:"INSERT",schema:"public",table:"messages",filter:"recipient_id=eq."+initialProfile.id},(payload)=>{const m=payload.new as any;if(selected&&(m.sender_id===selected.id||m.recipient_id===selected.id))setMessages(v=>[...v,m]);loadChats();}).subscribe();return()=>{supabase.removeChannel(channel)};},[selected]);
 function pickFile(e:ChangeEvent<HTMLInputElement>){const f=e.target.files?.[0]||null;setFile(f);setPreview(f?URL.createObjectURL(f):"");}
 async function createPost(e:FormEvent){e.preventDefault();setPosting(true);setNotice("");try{let path:null|string=null;let type:null|string=null;if(file){if(file.size>25*1024*1024)throw new Error("Media must be 25 MB or smaller.");const ext=file.name.split(".").pop()?.toLowerCase()||"bin";path=initialProfile.id+"/"+crypto.randomUUID()+"."+ext;const up=await supabase.storage.from("media").upload(path,file,{upsert:false,contentType:file.type});if(up.error)throw up.error;type=file.type.startsWith("video/")?"video":"image";}const{error}=await supabase.from("posts").insert({author_id:initialProfile.id,caption:caption.trim(),media_path:path,media_type:type});if(error)throw error;setCaption("");setFile(null);setPreview("");setShowCreate(false);await loadPosts();}catch(err:any){setNotice(err?.message||"Unable to publish post.");}finally{setPosting(false);}}
 async function toggleLike(p:Post){if(p.liked)await supabase.from("likes").delete().eq("post_id",p.id).eq("user_id",initialProfile.id);else await supabase.from("likes").insert({post_id:p.id,user_id:initialProfile.id});await loadPosts();}
 async function toggleSave(p:Post){if(saved.includes(p.id))await supabase.from("saved_posts").delete().eq("post_id",p.id).eq("user_id",initialProfile.id);else await supabase.from("saved_posts").insert({post_id:p.id,user_id:initialProfile.id});const{data}=await supabase.from("saved_posts").select("post_id").eq("user_id",initialProfile.id);setSaved((data||[]).map((x:any)=>x.post_id));}
 async function addComment(p:Post,body:string){const{error}=await supabase.from("comments").insert({post_id:p.id,user_id:initialProfile.id,body:body.trim()});if(error)setNotice(error.message);else await loadPosts();}
 async function toggleFollow(p:Profile){if(followed.includes(p.id)){await supabase.from("follows").delete().eq("follower_id",initialProfile.id).eq("following_id",p.id);setFollowed(v=>v.filter(x=>x!==p.id));}else{const{error}=await supabase.from("follows").insert({follower_id:initialProfile.id,following_id:p.id});if(!error)setFollowed(v=>[...v,p.id]);}}
 async function sendMessage(){if(!selected||!message.trim())return;const{data,error}=await supabase.from("messages").insert({sender_id:initialProfile.id,recipient_id:selected.id,body:message.trim()}).select("*").single();if(error)setNotice(error.message);else{setMessages(v=>[...v,data]);setMessage("");await loadChats();}}
 async function signOut(){await supabase.auth.signOut();window.location.href="/auth";}
 const filteredPeople=people.filter(p=>(p.display_name+" "+p.username).toLowerCase().includes(query.toLowerCase()));
 const media=(path:string)=>supabase.storage.from("media").getPublicUrl(path).data.publicUrl;
 return <div className="social-app"><header className="top"><button className="brand" onClick={()=>setScreen("home")}><i/>AVENZO</button><div className="search-wrap"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search people & posts"/></div><button className="top-profile" onClick={()=>setScreen("profile")}><img src={avatar(profile)} className="avatar"/><span>@{profile.username}</span></button></header><div className="social-layout"><aside className="left-nav">{[["home","Home"],["explore","Explore"],["messages","Messages"],["activity","Activity"],["saved","Saved"],["profile","Profile"],["settings","Settings"]].map(([id,label])=><button key={id} className={screen===id?"active":""} onClick={()=>setScreen(id)}>{label}</button>)}<button className="create-nav" onClick={()=>setShowCreate(true)}>＋ Create</button><button className="logout-nav" onClick={signOut}>↪ Sign out</button></aside><main className="social-main">
 {screen==="home"&&<><section className="welcome"><div><div className="eyebrow">YOUR AVENZO</div><h1>Share life with your people.</h1><p>Posts, conversations and real connections, under your own identity.</p></div><button className="btn" onClick={()=>setShowCreate(true)}>Create post</button></section><div className="stories-row"><div className="story"><img src={avatar(profile)}/><small>Your story</small></div>{people.slice(0,7).map(p=><button className="story" key={p.id} onClick={()=>setScreen("explore")}><img src={avatar(p)}/><small>@{p.username}</small></button>)}</div>{loading?<div className="empty">Loading your feed…</div>:posts.length===0?<div className="empty"><b>Your feed is empty.</b><br/>Find people in Explore and publish the first AVENZO post.</div>:posts.map(p=><PostCard key={p.id} post={p} liked={p.liked} saved={saved.includes(p.id)} mediaUrl={p.media_path?media(p.media_path):""} onLike={()=>toggleLike(p)} onSave={()=>toggleSave(p)} onComment={x=>addComment(p,x)}/>)}</>}
 {screen==="explore"&&<><div className="section-title"><div className="eyebrow">DISCOVER</div><h2>Explore</h2><p>Real AVENZO accounts.</p></div><div className="people-grid">{filteredPeople.map(p=><div className="person-card" key={p.id}><img className="person-avatar" src={avatar(p)}/><b>{p.display_name}</b><span>@{p.username}</span><p>{p.bio||"New to AVENZO."}</p><button className="btn small" onClick={()=>toggleFollow(p)}>{followed.includes(p.id)?"Following":"Follow"}</button><button className="btn secondary small" onClick={()=>{openChat(p);setScreen("messages")}}>Message</button></div>)}{filteredPeople.length===0&&<div className="empty">No other registered users yet.</div>}</div></>}
 {screen==="saved"&&<><div className="section-title"><div className="eyebrow">COLLECTION</div><h2>Saved</h2></div>{posts.filter(p=>saved.includes(p.id)).map(p=><PostCard key={p.id} post={p} liked={p.liked} saved mediaUrl={p.media_path?media(p.media_path):""} onLike={()=>toggleLike(p)} onSave={()=>toggleSave(p)} onComment={x=>addComment(p,x)}/>) }{saved.length===0&&<div className="empty">Nothing saved yet.</div>}</>}
 {screen==="activity"&&<Activity supabase={supabase} userId={initialProfile.id}/>}
 {screen==="profile"&&<ProfileView profile={profile} posts={posts.filter(p=>p.author_id===profile.id)} media={media}/>}
 {screen==="settings"&&<Settings profile={profile} setProfile={setProfile} supabase={supabase} signOut={signOut}/>}
 {screen==="messages"&&<Messages people={filteredPeople} chats={chats} selected={selected} openChat={openChat} messages={messages} userId={initialProfile.id} text={message} setText={setMessage} send={sendMessage}/>}</main><aside className="right-rail"><div className="side-card"><div className="side-card-head"><b>People to follow</b><button onClick={()=>setScreen("explore")}>See all</button></div>{people.slice(0,4).map(p=><div className="mini-person" key={p.id}><img src={avatar(p)}/><div><b>{p.display_name}</b><small>@{p.username}</small></div><button onClick={()=>toggleFollow(p)}>{followed.includes(p.id)?"✓":"Follow"}</button></div>)}</div></aside></div><nav className="mobile-nav">{[["home","Home"],["explore","Explore"],["create","Create"],["messages","Chat"],["profile","Profile"]].map(([id,label])=><button key={id} className={screen===id?"active":""} onClick={()=>id==="create"?setShowCreate(true):setScreen(id)}>{label}</button>)}</nav>{showCreate&&<div className="modal"><form className="modal-box" onSubmit={createPost}><div className="eyebrow">CREATE</div><h2>New post</h2><textarea value={caption} onChange={e=>setCaption(e.target.value)} placeholder="Share something with your people…"/><input type="file" accept="image/*,video/*" onChange={pickFile}/>{preview&&(file?.type.startsWith("video/")?<video src={preview} controls className="upload-preview"/>:<img src={preview} className="upload-preview"/>)}{notice&&<div className="notice">{notice}</div>}<div className="modal-actions"><button type="button" className="btn secondary" onClick={()=>setShowCreate(false)}>Cancel</button><button className="btn" disabled={posting}>{posting?"Publishing…":"Publish"}</button></div></form></div>}</div>;
}
function PostCard({post,liked,saved,mediaUrl,onLike,onSave,onComment}:{post:Post;liked:boolean;saved:boolean;mediaUrl:string;onLike:()=>void;onSave:()=>void;onComment:(x:string)=>void}){const[c,setC]=useState("");return <article className="post-card"><div className="post-head"><div className="person-line"><img src={post.profile?.avatar_url||blankAvatar(post.profile?.display_name||"A")}/><div><b>{post.profile?.display_name||"AVENZO user"}</b><small>@{post.profile?.username||"user"}</small></div></div><span className="muted">•••</span></div>{post.media_path&&post.media_type==="image"&&<img className="post-media" src={mediaUrl} alt="Post"/>}{post.media_path&&post.media_type==="video"&&<video className="post-media" src={mediaUrl} controls/>}<div className="post-content"><p>{post.caption}</p><div className="post-actions"><button className={liked?"liked":""} onClick={onLike}>♡ {post.likeCount}</button><button>◌ {post.commentCount}</button><button className="save-action" onClick={onSave}>{saved?"Saved":"Save"}</button></div><div className="comment-list">{post.comments.slice(-3).map(c=><div key={c.id}><b>@{c.profile?.username||"user"}</b> {c.body}</div>)}<form onSubmit={e=>{e.preventDefault();if(c.trim()){onComment(c);setC("")}}} className="comment-input"><input value={c} onChange={e=>setC(e.target.value)} placeholder="Add a comment…"/><button>Post</button></form></div></div></article>}
function Messages({people,chats,selected,openChat,messages,userId,text,setText,send}:{people:Profile[];chats:Chat[];selected:Profile|null;openChat:(p:Profile)=>void;messages:any[];userId:string;text:string;setText:(s:string)=>void;send:()=>void}){const list=chats.map(c=>c.profile).concat(people.filter(p=>!chats.some(c=>c.profile.id===p.id)).slice(0,10));return <div className="chat"><div className="chat-list">{list.map(p=><button className={"chat-user "+(selected?.id===p.id?"active":"")} key={p.id} onClick={()=>openChat(p)}><img src={p.avatar_url||blankAvatar(p.display_name)}/><span><b>{p.display_name}</b><small>@{p.username}</small></span></button>)}</div><div className="chat-main">{selected?<><div className="chat-head"><img src={selected.avatar_url||blankAvatar(selected.display_name)}/><div><b>{selected.display_name}</b><small>@{selected.username}</small></div></div><div className="chat-body">{messages.map(m=><div key={m.id} className={"bubble "+(m.sender_id===userId?"me":"")}>{m.body}</div>)}</div><div className="chat-compose"><input value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>e.key==="Enter"&&send()} placeholder="Write a message…"/><button className="btn" onClick={send}>Send</button></div></>:<div className="empty">Choose a registered user to start a conversation.</div>}</div></div>}
function Activity({supabase,userId}:{supabase:any;userId:string}){const[data,setData]=useState<any[]>([]);useEffect(()=>{supabase.from("notifications").select("id,type,created_at,actor_id").eq("recipient_id",userId).order("created_at",{ascending:false}).limit(30).then(({data}:any)=>setData(data||[]))},[supabase,userId]);return <><div className="section-title"><div className="eyebrow">ACTIVITY</div><h2>Notifications</h2></div>{data.length===0?<div className="empty">No activity yet.</div>:data.map(n=><div className="notification" key={n.id}><b>{n.type==="follow"?"Someone followed you":n.type==="like"?"Someone liked your post":n.type==="comment"?"Someone commented on your post":"New message"}</b><small>{new Date(n.created_at).toLocaleString()}</small></div>)}</>}
function ProfileView({profile,posts,media}:{profile:Profile;posts:Post[];media:(x:string)=>string}){return <><div className="profile-hero"><img src={profile.avatar_url||blankAvatar(profile.display_name)}/><div><div className="eyebrow">@{profile.username}</div><h1>{profile.display_name}</h1><p>{profile.bio||"Welcome to AVENZO."}</p><div className="profile-stats"><span><b>{posts.length}</b> posts</span><span><b>—</b> followers</span><span><b>—</b> following</span></div></div></div><div className="grid">{posts.filter(p=>p.media_path).map(p=><img key={p.id} src={media(p.media_path!)} alt="Post"/>)}</div></>}
function Settings({profile,setProfile,supabase,signOut}:{profile:Profile;setProfile:(p:Profile)=>void;supabase:any;signOut:()=>void}){const[n,setN]=useState(profile.display_name),[b,setB]=useState(profile.bio),[notice,setNotice]=useState("");async function save(){const{data,error}=await supabase.from("profiles").update({display_name:n.trim(),bio:b.trim()}).eq("id",profile.id).select("*").single();if(error)setNotice(error.message);else{setProfile(data);setNotice("Profile saved.");}}return <><div className="section-title"><div className="eyebrow">ACCOUNT</div><h2>Settings</h2></div><div className="settings-card"><label>Username</label><input value={"@"+profile.username} readOnly/><label>Display name</label><input value={n} onChange={e=>setN(e.target.value)}/><label>Bio</label><textarea value={b} onChange={e=>setB(e.target.value)}/><button className="btn" onClick={save}>Save changes</button>{notice&&<p className="muted">{notice}</p>}<button className="btn secondary" onClick={signOut}>Sign out</button></div></>}