create table if not exists public.call_sessions (
  id uuid primary key default gen_random_uuid(),
  conversation_id uuid not null references public.conversations(id) on delete cascade,
  caller_id uuid not null references public.profiles(id) on delete cascade,
  callee_id uuid not null references public.profiles(id) on delete cascade,
  status text not null default 'ringing'
    check (status in ('ringing','accepted','declined','ended','missed')),
  created_at timestamptz not null default now(),
  answered_at timestamptz,
  ended_at timestamptz,
  constraint call_sessions_distinct_users check (caller_id <> callee_id)
);

create table if not exists public.call_signals (
  id bigint generated by default as identity primary key,
  call_id uuid not null references public.call_sessions(id) on delete cascade,
  sender_id uuid not null references public.profiles(id) on delete cascade,
  recipient_id uuid not null references public.profiles(id) on delete cascade,
  signal_type text not null check (signal_type in ('offer','answer','ice')),
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists call_sessions_callee_status_idx
  on public.call_sessions(callee_id,status,created_at desc);
create index if not exists call_sessions_caller_status_idx
  on public.call_sessions(caller_id,status,created_at desc);
create index if not exists call_signals_recipient_idx
  on public.call_signals(recipient_id,created_at);

alter table public.call_sessions enable row level security;
alter table public.call_signals enable row level security;

drop policy if exists call_sessions_participant_read on public.call_sessions;
create policy call_sessions_participant_read
on public.call_sessions for select to authenticated
using (
  caller_id = (select auth.uid())
  or callee_id = (select auth.uid())
);

drop policy if exists call_sessions_caller_insert on public.call_sessions;
create policy call_sessions_caller_insert
on public.call_sessions for insert to authenticated
with check (
  caller_id = (select auth.uid())
  and public.is_conversation_participant(conversation_id,(select auth.uid()))
  and exists (
    select 1
    from public.conversation_participants cp
    where cp.conversation_id = call_sessions.conversation_id
      and cp.user_id = call_sessions.callee_id
      and cp.left_at is null
  )
);

drop policy if exists call_sessions_participant_update on public.call_sessions;
create policy call_sessions_participant_update
on public.call_sessions for update to authenticated
using (
  caller_id = (select auth.uid())
  or callee_id = (select auth.uid())
)
with check (
  caller_id = (select auth.uid())
  or callee_id = (select auth.uid())
);

drop policy if exists call_signals_participant_read on public.call_signals;
create policy call_signals_participant_read
on public.call_signals for select to authenticated
using (
  sender_id = (select auth.uid())
  or recipient_id = (select auth.uid())
);

drop policy if exists call_signals_sender_insert on public.call_signals;
create policy call_signals_sender_insert
on public.call_signals for insert to authenticated
with check (
  sender_id = (select auth.uid())
  and exists (
    select 1
    from public.call_sessions cs
    where cs.id = call_signals.call_id
      and (
        cs.caller_id = (select auth.uid())
        or cs.callee_id = (select auth.uid())
      )
      and call_signals.recipient_id in (cs.caller_id, cs.callee_id)
      and call_signals.recipient_id <> (select auth.uid())
  )
);

do $realtime_calls$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname='supabase_realtime'
      and schemaname='public'
      and tablename='call_sessions'
  ) then
    alter publication supabase_realtime add table public.call_sessions;
  end if;

  if not exists (
    select 1 from pg_publication_tables
    where pubname='supabase_realtime'
      and schemaname='public'
      and tablename='call_signals'
  ) then
    alter publication supabase_realtime add table public.call_signals;
  end if;
end
$realtime_calls$;
