-- AVENZO stability hardening: key integrity and foreign-key indexes.

alter table public.saved_collection_items
  add column if not exists id bigint generated by default as identity;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conrelid = 'public.saved_collection_items'::regclass
      and contype = 'p'
  ) then
    alter table public.saved_collection_items
      add constraint saved_collection_items_pkey primary key (id);
  end if;
end
$$;

create unique index if not exists saved_collection_items_collection_post_uq
  on public.saved_collection_items(collection_id, post_id)
  where post_id is not null;

create unique index if not exists saved_collection_items_collection_reel_uq
  on public.saved_collection_items(collection_id, reel_id)
  where reel_id is not null;

create index if not exists broadcast_channel_posts_author_idx
  on public.broadcast_channel_posts(author_id);

create index if not exists broadcast_channel_reactions_user_idx
  on public.broadcast_channel_reactions(user_id);

create index if not exists call_sessions_conversation_idx
  on public.call_sessions(conversation_id);

create index if not exists call_signals_call_idx
  on public.call_signals(call_id);

create index if not exists call_signals_sender_idx
  on public.call_signals(sender_id);

create index if not exists close_friends_friend_idx
  on public.close_friends(friend_id);

create index if not exists group_chats_created_by_idx
  on public.group_chats(created_by);

create index if not exists group_message_reactions_user_idx
  on public.group_message_reactions(user_id);

create index if not exists group_messages_reply_to_idx
  on public.group_messages(reply_to_id);

create index if not exists group_messages_sender_idx
  on public.group_messages(sender_id);

create index if not exists message_pins_pinned_by_idx
  on public.message_pins(pinned_by);

create index if not exists post_collaborators_invited_by_idx
  on public.post_collaborators(invited_by);

create index if not exists saved_collection_items_post_idx
  on public.saved_collection_items(post_id);

create index if not exists saved_collection_items_reel_idx
  on public.saved_collection_items(reel_id);

create index if not exists scheduled_messages_conversation_idx
  on public.scheduled_messages(conversation_id);

create index if not exists scheduled_messages_recipient_idx
  on public.scheduled_messages(recipient_id);

create index if not exists scheduled_messages_reply_to_idx
  on public.scheduled_messages(reply_to_id);

create index if not exists scheduled_messages_sent_message_idx
  on public.scheduled_messages(sent_message_id);

create index if not exists story_highlights_cover_story_idx
  on public.story_highlights(cover_story_id);
